# Generated by Django 4.2.25 on 2025-11-17 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('SERVICO', 'Serviço'), ('PRODUTO', 'Produto')], default='SERVICO', max_length=8, verbose_name='Tipo')),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço de venda')),
                ('controla_estoque', models.BooleanField(default=False, help_text='Marque apenas para itens físicos que baixam estoque.', verbose_name='Controla estoque?')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1, verbose_name='Tipo')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='estoque.produto')),
            ],
            options={
                'verbose_name': 'Movimento de estoque',
                'verbose_name_plural': 'Movimentos de estoque',
                'ordering': ['-data'],
            },
        ),
    ]
