# Generated by Django 4.2.25 on 2025-12-09 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_produto_movimentoestoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Código do lote impresso na embalagem (opcional).', max_length=50, verbose_name='Lote')),
                ('validade', models.DateField(blank=True, help_text='Data de validade do lote (se houver).', null=True, verbose_name='Validade')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='estoque.produto')),
            ],
            options={
                'verbose_name': 'Lote de produto',
                'verbose_name_plural': 'Lotes de produto',
                'ordering': ['produto', 'validade', 'codigo'],
            },
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='estoque.loteproduto', verbose_name='Lote'),
        ),
    ]
