# Generated by Django 4.2.27 on 2026-01-12 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('estoque', '0003_loteproduto_movimentoestoque_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estoque_produtos', to='core.empresa'),
            preserve_default=False,
        ),
    ]
