# Generated by Django 4.2.27 on 2026-01-16 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_empresa_codigo_alter_perfil_empresa_and_more'),
        ('estoque', '0004_produto_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteproduto',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_produto', to='core.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_estoque', to='core.empresa'),
            preserve_default=False,
        ),
    ]
