# Generated by Django 4.2.27 on 2026-01-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_loteproduto_empresa_movimentoestoque_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Quantidade mínima aceitável antes de gerar alerta.', max_digits=10, verbose_name='Estoque mínimo'),
        ),
    ]
