[tool.black]
line-length = 100
target-version = ["py313"]
include = '\.pyi?$'
exclude = '''
/(
  \.git
 | \.venv
 | venv
 | \.mypy_cache
 | \.pytest_cache
 | \.tox
 | build
 | dist
 | staticfiles
 | migrations
)/
'''
[tool.isort]
profile = "black"
line_length = 100
