# Generated by Django 4.2.27 on 2026-01-16 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_espaco'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='codigo',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Espaco',
        ),
    ]
