# Generated by Django 4.2.27 on 2026-01-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_empresa_codigo_alter_perfil_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='politica_lote_vencido',
            field=models.CharField(choices=[('bloquear', 'Bloquear sempre'), ('justificar', 'Permitir com justificativa'), ('livre', 'Permitir livre')], default='justificar', max_length=20),
        ),
    ]
