# Generated by Django 5.2.4 on 2025-07-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("codigo_barras", models.CharField(max_length=13, unique=True)),
                ("preco_venda", models.DecimalField(decimal_places=2, max_digits=10)),
                ("custo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("estoque", models.IntegerField()),
                ("categoria", models.CharField(max_length=50)),
                ("unidade", models.CharField(max_length=10)),
            ],
        ),
    ]
