# Generated by Django 5.2.4 on 2025-07-27 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("servicos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("data", models.DateField()),
                ("hora", models.TimeField()),
                ("telefone", models.CharField(blank=True, max_length=20, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servicos.servico",
                    ),
                ),
            ],
        ),
    ]
