# Generated by Django 5.2.4 on 2025-07-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="pet_nome",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
