# Generated by Django 5.2.4 on 2025-07-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0002_agendamento_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("confirmado", "Confirmado"),
                    ("concluido", "Concluído"),
                    ("cancelado", "Cancelado"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
    ]
