# Generated by Django 5.2.4 on 2025-08-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0004_alter_agendamento_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("agendado", "Agendado"),
                    ("concluido", "Concluído"),
                    ("cancelado", "Cancelado"),
                ],
                default="agendado",
                max_length=20,
            ),
        ),
    ]
