# Generated by Django 4.2.25 on 2025-12-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0005_alter_agendamento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('pendente', 'Pendente'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='agendado', max_length=20),
        ),
    ]
