# Generated by Django 4.2.27 on 2025-12-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0005_alter_agendamento_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agendamento",
            name="pet_nome",
        ),
        migrations.AddField(
            model_name="agendamento",
            name="pet_nome",
            field=models.CharField(default="Não informado", max_length=100),
            preserve_default=False,
        ),
    ]
