# Generated by Django 4.2.27 on 2025-12-31 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0006_alter_agendamento_status'),
        ('agendamentos', '0006_remove_agendamento_cliente_agendamento_pet_nome'),
    ]

    operations = [
    ]
