# Generated by Django 4.2.27 on 2026-01-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0006_remove_agendamento_cliente_agendamento_pet_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='pet_nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
