# Generated by Django 4.2.27 on 2026-01-13 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fix_perfil_sem_empresa'),
        ('agendamentos', '0007_alter_agendamento_pet_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='core.empresa'),
            preserve_default=False,
        ),
    ]
