# Generated by Django 4.2.25 on 2025-11-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço unitário'),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Quantidade'),
        ),
    ]
