# Generated by Django 4.2.27 on 2026-01-11 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('vendas', '0002_alter_itemvenda_preco_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='core.empresa'),
            preserve_default=False,
        ),
    ]
