# Generated by Django 4.2.27 on 2026-01-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_venda_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='justificativa_lote',
            field=models.TextField(blank=True, default='', verbose_name='Justificativa do lote'),
        ),
        migrations.AddField(
            model_name='venda',
            name='motivo_lote',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Motivo (lote)'),
        ),
    ]
