# Generated by Django 5.2.4 on 2025-08-15 13:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Despesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoria", models.CharField(default="Outros", max_length=100)),
                ("descricao", models.CharField(blank=True, max_length=255)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data", models.DateField()),
            ],
            options={
                "verbose_name": "Despesa",
                "verbose_name_plural": "Despesas",
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="Receita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("servico", models.CharField(max_length=100, verbose_name="Serviço")),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data", models.DateField()),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("banho", "Banho"),
                            ("tosa", "Tosa"),
                            ("venda", "Venda de Produto"),
                            ("outros", "Outros"),
                        ],
                        default="outros",
                        max_length=100,
                        verbose_name="Categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receita",
                "verbose_name_plural": "Receitas",
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="RecomendacaoIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("texto", models.TextField()),
                (
                    "categoria",
                    models.CharField(db_index=True, default="Geral", max_length=80),
                ),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("metrics", models.JSONField(default=dict)),
                (
                    "fingerprint",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("source", models.CharField(default="auto", max_length=20)),
                (
                    "generated_by",
                    models.CharField(default="rule_engine_v1", max_length=50),
                ),
                ("visible", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["period_start", "period_end"],
                        name="financeiro__period__4e4b4a_idx",
                    ),
                    models.Index(
                        fields=["categoria", "created_at"],
                        name="financeiro__categor_d7bdc3_idx",
                    ),
                ],
            },
        ),
    ]
