# Generated by Django 5.2.4 on 2025-08-16 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaCategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoria", models.CharField(db_index=True, max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("receita", "Receita"), ("despesa", "Despesa")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "mes",
                    models.DateField(db_index=True, help_text="Use o 1º dia do mês"),
                ),
                ("valor_meta", models.DecimalField(decimal_places=2, max_digits=10)),
                ("criado_em", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Meta por categoria",
                "verbose_name_plural": "Metas por categoria",
                "ordering": ["-mes", "categoria", "tipo"],
                "unique_together": {("categoria", "tipo", "mes")},
            },
        ),
    ]
