# Generated by Django 5.2.4 on 2025-08-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0002_metacategoria"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaCategoriaMensal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoria", models.CharField(db_index=True, max_length=100)),
                (
                    "ano_mes",
                    models.DateField(db_index=True, help_text="Use o 1º dia do mês"),
                ),
                (
                    "meta_receita",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "meta_despesa",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Meta por categoria (mês)",
                "verbose_name_plural": "Metas por categoria (mês)",
                "ordering": ["-ano_mes", "categoria"],
                "unique_together": {("categoria", "ano_mes")},
            },
        ),
    ]
