# Generated by Django 5.2.4 on 2025-08-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0003_metacategoriamensal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Insight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=180)),
                ("text", models.TextField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("TIP", "Dica"),
                            ("ALERT", "Alerta"),
                            ("INFO", "Informação"),
                        ],
                        default="TIP",
                        max_length=10,
                    ),
                ),
                (
                    "category_dominante",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("generated_by", models.CharField(default="manual", max_length=20)),
            ],
        ),
    ]
