# Generated by Django 5.2.4 on 2025-08-28 20:05
from decimal import Decimal

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0004_insight"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="metacategoria",
            options={"ordering": ["categoria"]},
        ),
        migrations.AlterUniqueTogether(
            name="metacategoria",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="metacategoria",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="metacategoria",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="metacategoria",
            name="teto",
            field=models.DecimalField(
                max_digits=12,
                decimal_places=2,
                default=Decimal("0"),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="metacategoria",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="metacategoria",
            name="categoria",
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.RemoveField(
            model_name="metacategoria",
            name="criado_em",
        ),
        migrations.RemoveField(
            model_name="metacategoria",
            name="mes",
        ),
        migrations.RemoveField(
            model_name="metacategoria",
            name="tipo",
        ),
        migrations.RemoveField(
            model_name="metacategoria",
            name="valor_meta",
        ),
    ]
