# Generated by Django 5.2.4 on 2025-10-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0005_alter_metacategoria_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("receita", "Receita"), ("despesa", "Despesa")], max_length=10
                    ),
                ),
                ("descricao", models.CharField(max_length=100)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data", models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name="Despesa",
        ),
        migrations.DeleteModel(
            name="Insight",
        ),
        migrations.DeleteModel(
            name="MetaCategoria",
        ),
        migrations.DeleteModel(
            name="MetaCategoriaMensal",
        ),
        migrations.DeleteModel(
            name="Receita",
        ),
        migrations.DeleteModel(
            name="RecomendacaoIA",
        ),
    ]
