# Generated by Django 5.2.4 on 2025-10-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0006_transacao_delete_despesa_delete_insight_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Insight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("title", models.CharField(max_length=120)),
                ("text", models.TextField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("financeiro", "Financeiro"),
                            ("meta", "Meta"),
                            ("alerta", "Alerta"),
                        ],
                        default="financeiro",
                        max_length=30,
                    ),
                ),
                ("categoria_dominante", models.CharField(blank=True, default="", max_length=50)),
                ("score", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
