# Generated by Django 5.2.4 on 2025-10-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0008_recomendacaoia"),
    ]

    operations = [
        migrations.AddField(
            model_name="insight",
            name="generated_by",
            field=models.CharField(default="manual", max_length=16),
        ),
    ]
