# Generated by Django 4.2.25 on 2025-11-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_insight_generated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
