# Generated by Django 4.2.25 on 2025-11-22 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_alter_itemvenda_preco_unitario_and_more'),
        ('financeiro', '0010_transacao_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='vendas.venda', verbose_name='Venda relacionada'),
        ),
    ]
