# Generated by Django 4.2.25 on 2025-11-27 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeiro', '0011_transacao_venda'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('tipo', models.CharField(choices=[('positiva', 'Positiva'), ('alerta', 'Alerta'), ('neutra', 'Neutra')], default='neutra', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('origem', models.CharField(default='manual', help_text='Origem da recomendação', max_length=20)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
