# Generated by Django 4.2.27 on 2026-01-11 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_alter_itemvenda_preco_unitario_and_more'),
        ('financeiro', '0012_historicoia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='venda',
        ),
        migrations.AddField(
            model_name='transacao',
            name='vendas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='vendas.venda', verbose_name='Vendas relacionada'),
        ),
    ]
