# Generated by Django 4.2.27 on 2026-01-12 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_venda_empresa'),
        ('core', '0001_initial'),
        ('financeiro', '0013_remove_transacao_venda_transacao_vendas'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='core.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transacao',
            name='vendas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='vendas.venda', verbose_name='Venda relacionada'),
        ),
    ]
