# Generated by Django 4.2.27 on 2026-01-11 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendaitem',
            old_name='venda',
            new_name='vendas',
        ),
    ]
