# Generated by Django 4.2.27 on 2026-01-11 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_loteproduto_movimentoestoque_lote'),
        ('pdv', '0002_rename_venda_vendaitem_vendas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendaitem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.produto'),
        ),
    ]
