# Generated by Django 4.2.27 on 2026-01-13 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fix_perfil_sem_empresa'),
        ('estoque', '0004_produto_empresa'),
        ('pdv', '0003_alter_vendaitem_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pdv_vendas', to='core.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendaitem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pdv_itens', to='estoque.produto'),
        ),
    ]
