# Generated by Django 4.2.27 on 2026-01-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0004_venda_empresa_alter_vendaitem_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='justificativa_lote',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
