# Generated by Django 4.2.27 on 2026-01-25 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_produto_estoque_minimo'),
        ('core', '0005_empresa_politica_lote_vencido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdv', '0005_venda_justificativa_lote'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverrideLoteVencido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('ACAO_IMEDIATA', 'Ação imediata'), ('ALERTA_7_DIAS', 'Alerta 7 dias'), ('ALERTA_15_DIAS', 'Alerta 15 dias'), ('ATENCAO', 'Atenção')], default='ACAO_IMEDIATA', max_length=20)),
                ('motivo', models.CharField(default='', max_length=255)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pdv_overrides', to='core.empresa')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdv_overrides', to='estoque.loteproduto')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdv_overrides', to='estoque.produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pdv_overrides', to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overrides', to='pdv.venda')),
            ],
        ),
    ]
