# Generated by Django 4.2.25 on 2025-11-24 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('destino', models.CharField(help_text='chat_id do Telegram ou número do WhatsApp em formato internacional.', max_length=100)),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('mensagem', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('erro_msg', models.TextField(blank=True, help_text='Mensagem de erro retornada pela API, se houver.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, help_text='Dono da conta que vai receber a mensagem.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
