# Generated by Django 4.2.25 on 2025-11-24 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalNotificacaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('destino', models.CharField(help_text='chat_id do Telegram ou número do WhatsApp (formato internacional).', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canais_notificacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Canal de notificação do usuário',
                'verbose_name_plural': 'Canais de notificação dos usuários',
                'unique_together': {('usuario', 'canal', 'ativo')},
            },
        ),
    ]
