# Generated by Django 4.2.25 on 2025-11-27 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notificacoes', '0002_canalnotificacaousuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoIAAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('origem', models.CharField(default='auto', help_text="Origem da dica (ex.: 'auto', 'cron', 'manual').", max_length=32)),
                ('tipo', models.CharField(blank=True, help_text='Tipo retornado pela IA (positiva / alerta / neutra...).', max_length=20)),
                ('texto', models.TextField(help_text='Texto da dica enviada (ou gerada) pela IA.')),
                ('canal', models.CharField(default='telegram', help_text='Canal de envio: telegram / whatsapp / outro.', max_length=20)),
                ('sucesso_envio', models.BooleanField(default=False, help_text='True se o envio para o canal externo foi bem-sucedido.')),
                ('erro_envio', models.TextField(blank=True, help_text='Mensagem de erro do envio, se houver.')),
                ('meta', models.JSONField(blank=True, help_text='Payload extra da análise (ex.: dict com inicio/fim, saldo, etc).', null=True)),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuário dono do contexto da análise (se aplicável).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Execução IA automática',
                'verbose_name_plural': 'Execuções IA automáticas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
